// SPDX-License-Identifier: AGPL-3.0-only
package org.nonverba.camera

/** Deterministic diagnostics guards only; this is not a physical receiver test. */
fun main() {
    var passed = 0
    fun equal(actual: Any?, expected: Any?) { check(actual == expected) { "$actual != $expected" }; passed++ }
    fun satellite(constellation: Int = 1, used: Boolean = false, cn0: Double = 30.0) =
        NativeGnssStatusDiagnostics.Satellite(constellation, used, cn0)
    val status = NativeGnssStatusDiagnostics()
    equal(status.snapshot().registration, NativeGnssStatusDiagnostics.Registration.NOT_ATTEMPTED)
    equal(status.snapshot().observation, null)
    equal(status.callback(100), false)
    equal(status.registrationAttempt(), true)
    equal(status.registrationAttempt(), false)
    status.registrationResult(true)
    // Successful registration is not an observation of zero satellites or a raw-capability claim.
    equal(status.snapshot().observation, null)
    equal(status.snapshot().callbackCount, 0)
    equal(status.callback(1200), true)
    status.observe(listOf(satellite(1, true, 20.0), satellite(1, false, 40.0), satellite(6, true, 30.0)))
    val first = status.snapshot()
    equal(first.lastCallbackElapsedMs, 1200L)
    equal(first.observation?.satelliteCount, 3)
    equal(first.observation?.usedInFixCount, 2)
    equal(first.observation?.cn0SampleCount, 3)
    equal(first.observation?.cn0MinDbHz, 20.0)
    equal(first.observation?.cn0MeanDbHz, 30.0)
    equal(first.observation?.cn0MaxDbHz, 40.0)
    equal(first.observation?.constellationCounts, mapOf("gps" to 2, "galileo" to 1))
    status.callback(2200)
    // A failed new read clears the former observation instead of relabelling old values as current.
    equal(status.snapshot().observation, null)
    status.unreadableCallback()
    equal(status.snapshot().unreadableCallbacks, 1)
    equal(first.observation?.satelliteCount, 3)
    status.callback(3200)
    status.observe(listOf(satellite(8, true, Double.NaN), satellite(-1, false, Double.POSITIVE_INFINITY),
        satellite(2, false, -0.01), satellite(3, true, 63.01), satellite(4, true, 0.0), satellite(5, false, 63.0)))
    val invalid = status.snapshot().observation!!
    equal(invalid.satelliteCount, 6)
    equal(invalid.usedInFixCount, 3)
    equal(invalid.cn0SampleCount, 2)
    equal(invalid.invalidCn0Count, 4)
    equal(invalid.cn0MinDbHz, 0.0)
    equal(invalid.cn0MeanDbHz, 31.5)
    equal(invalid.cn0MaxDbHz, 63.0)
    equal(invalid.constellationCounts["unknown"], 2)
    status.callback(4200)
    status.observe(emptyList())
    val empty = status.snapshot().observation!!
    equal(empty.satelliteCount, 0)
    equal(empty.usedInFixCount, 0)
    equal(empty.cn0SampleCount, 0)
    equal(empty.cn0MeanDbHz, null)
    equal(empty.constellationCounts, emptyMap<String, Int>())
    status.callback(5200)
    status.observe(List(NativeGnssStatusDiagnostics.MAX_SATELLITES + 1) { satellite() })
    equal(status.snapshot().observation, null)
    equal(status.snapshot().unreadableCallbacks, 2)
    status.callback(6200)
    status.observe(List(NativeGnssStatusDiagnostics.MAX_SATELLITES) { satellite(7, true) })
    equal(status.snapshot().observation?.satelliteCount, 256)
    equal(status.snapshot().observation?.constellationCounts, mapOf("irnss" to 256))
    status.stop()
    val frozen = status.snapshot()
    equal(frozen.active, false)
    equal(status.callback(7200), false)
    status.observe(listOf(satellite()))
    status.unreadableCallback()
    status.stop()
    equal(status.snapshot(), frozen)
    equal(status.registrationAttempt(), false)
    // A fresh session has no inherited counters or satellite data.
    val replacement = NativeGnssStatusDiagnostics()
    equal(replacement.snapshot().callbackCount, 0)
    equal(replacement.snapshot().observation, null)
    replacement.registrationAttempt()
    replacement.registrationResult(false)
    equal(replacement.callback(1), false)
    equal(replacement.snapshot().registration, NativeGnssStatusDiagnostics.Registration.REFUSED)
    replacement.registrationException()
    equal(replacement.snapshot().registration, NativeGnssStatusDiagnostics.Registration.EXCEPTION)
    replacement.cleanupFailure()
    equal(replacement.snapshot().cleanupFailed, true)
    val bounded = NativeGnssStatusDiagnostics()
    bounded.registrationAttempt()
    bounded.callback(-1)
    equal(bounded.snapshot().lastCallbackElapsedMs, null)
    bounded.callback(Long.MAX_VALUE)
    equal(bounded.snapshot().lastCallbackElapsedMs, null)
    repeat(NativeGnssStatusDiagnostics.MAX_CALLBACKS + 2) { bounded.callback(1); bounded.unreadableCallback() }
    equal(bounded.snapshot().callbackCount, NativeGnssStatusDiagnostics.MAX_CALLBACKS)
    equal(bounded.snapshot().unreadableCallbacks, NativeGnssStatusDiagnostics.MAX_CALLBACKS)
    println("Native GNSS status diagnostic checks passed: $passed (unsigned summaries, no Android/RF validation)")
}
